source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

group :development do
  gem 'ruby-debug-ide', '~> 0.7.2'
  gem 'debase', '~> 0.2.4.1'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', "~> 4.0.0"
  gem 'simplecov', '~> 0.20'
  gem 'codecov', '~> 0.4'
end

group :test do
  gem 'mock_redis'
end

if ENV['COSMOS_DEVEL']
  gem 'cosmos', :path => ENV['COSMOS_DEVEL']
elsif ENV['COSMOS_PATH']
  gem 'cosmos', :path => ENV['COSMOS_PATH']
else
  gem 'cosmos', '~> 5'
end
